apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
  namespace: ghost
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghost
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: ghost:5
          ports:
            - containerPort: 2368
          env:
            - name: database__client
              value: "mysql"

            - name: database__connection__host
              valueFrom:
                secretKeyRef:
                  name: ghost-db-secret
                  key: host

            - name: database__connection__user
              valueFrom:
                secretKeyRef:
                  name: ghost-db-secret
                  key: username

            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghost-db-secret
                  key: password

            - name: database__connection__database
              valueFrom:
                secretKeyRef:
                  name: ghost-db-secret
                  key: database

            - name: server__host
              value: "0.0.0.0"

          readinessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 2368
            initialDelaySeconds: 60
            periodSeconds: 20
