apiVersion: v1
kind: Service
metadata:
  name: ghost
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: ghost
  ports:
    - port: 80
      targetPort: 2368
  type: LoadBalancer
